
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "8000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: attendance-app
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=attendance
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  postgres-data: